In [3]:
import pandas as pd  # for data handling

ratings = pd.read_csv("../data/raw/ml-25m/ratings.csv")  # load dataset

print(ratings.shape)  # check size

print(ratings.dtypes)  # check types

ratings.head()  # preview data

(25000095, 4)
userId         int64
movieId        int64
rating       float64
timestamp      int64
dtype: object

   userId  movieId  rating   timestamp
0       1      296     5.0  1147880044
1       1      306     3.5  1147868817
2       1      307     5.0  1147868828
3       1      665     5.0  1147878820
4       1      899     3.5  1147868510

In [4]:
import duckdb  # in-memory SQL database engine

sql = open("../sql/sessionize.sql").read()  # read SQL query from file
conn = duckdb.connect(database=":memory:")  # create temporary in-memory DB

sessions_df = conn.execute(sql).df()  # run query and get result as DataFrame
print("sessions:", sessions_df.shape)  # check result size
sessions_df.head()  # preview result

sessions: (25000095, 4)

   user_id  item_id  timestamp  session_id
0      122      592  848691888         1.0
1      122      150  848691889         1.0
2      122      296  848691889         1.0
3      122      380  848691889         1.0
4      122      590  848691889         1.0